[Variables]
fontNameSmall=Ubuntu Mono
fontNameBig=Microgramma D
fontSizeSmall=8
fontSizeMedium=16
fontSizeBig=24
colorBar=255,255,255,200
colorTextLight=255,255,255,205
colorTextDark=105,105,105,205
barWidth=36
barHeight=9

[styleLeftTextBig]
StringAlign=Left
;StringCase=UPPER
StringStyle=Normal
FontColor=#colorTextLight#
FontFace=#fontNameBig#
FontSize=#fontSizeBig#
AntiAlias=1
ClipString=0
InlineSetting=CharacterSpacing | 0 | 1
;InlineSetting=Typography | fwid

[styleRightTextBig]
StringAlign=Right
;StringCase=UPPER
StringStyle=Normal
FontColor=#colorTextLight#
FontFace=#fontNameBig#
FontSize=#fontSizeBig#
AntiAlias=1
ClipString=1
;InlineSetting=Typography | fwid

[styleLeftText]
StringAlign=Left
;StringCase=UPPER
StringStyle=Normal
FontColor=#colorTextLight#
FontFace=#fontNameSmall#
FontSize=#fontSizeSmall#
AntiAlias=0
ClipString=1
;InlineSetting=Typography | fwid

[styleLeftText]
StringAlign=Left
;StringCase=UPPER
StringStyle=Normal
FontColor=#colorTextLightDark#
FontFace=#fontNameSmall#
FontSize=#fontSizeSmall#
AntiAlias=0
ClipString=1
;InlineSetting=Typography | fwid

[styleRightText]
StringAlign=Right
StringCase=UPPER
StringStyle=Normal
FontColor=#colorTextLight#
FontFace=#fontNameSmall#
FontSize=#fontSizeSmall#
AntiAlias=0
ClipString=1
;InlineSetting=Typography | fwid

[styleBar]
BarColor=#colorBar#
BarOrientation=HORIZONTAL
SolidColor=255,255,255,127
