[styleLeftText]
StringAlign=Left
;StringCase=UPPER
StringStyle=Normal
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=0
ClipString=1
;InlineSetting=Typography | fwid

[styleRightText]
StringAlign=Right
StringCase=UPPER
StringStyle=Normal
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=0
ClipString=1
;InlineSetting=Typography | fwid

[styleBar]
BarColor=#colorBar#
BarOrientation=HORIZONTAL
SolidColor=255,255,255,127
